oneshot: false

reverse_tf: false

localization_freq: 100

initial_guess:
        pos: [1.5, 1.0, 0]
        rpy: [0, 0, 0]

registration:
        scan_stack_size: 10
        init:
                map_voxel_size: 0.1
                scan_voxel_size: 0.1
                max_corres_dist: 0.2
                localization_thresh: 0.8
                map_range: 10.0
                scan_range: 10.0 
        float:
                map_voxel_size: 0.1
                scan_voxel_size: 0.1
                max_corres_dist: 0.2
                localization_thresh: 0.8
                map_range: 5.0 
                scan_range: 5.0
        fix:
                map_voxel_size: 0.02
                scan_voxel_size: 0.02
                max_corres_dist: 0.04
                localization_thresh: 0.9
                map_range: 3.0
                scan_range: 3.0
